export const sample_products: any[] = [
  {
    id: "Loaf1",
    name: "Brown Rice Milk Loaf",
    description: "",
    price: {half:14,whole:16},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "sugar", "natural sea salt", "loaf"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 0,
    rating:3,
    category: "Loaf",
    status: "published"
  },
  {
    id: "Loaf2",
    name: "Wholemeal Loaf",
    description: "",
    price: {half:16,whole:30},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "wholemeal flour", "filtered water", "oil", "sugar", "natural sea salt", "oat", "loaf"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Loaf",
    status: "out stock"
  },
  {
    id: "Loaf3",
    name: "Wholemeal Raisin Loaf",
    description: "",
    price: {half:16.50,whole:31},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "wholemeal flour", "filtered water", "raisin", "oil", "sugar", "natural sea salt", "loaf"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Loaf",
    status: "inactive"
  },
  {
    id: "Loaf4",
    name: "Flaxseed & Chiaseed Loaf",
    description: "",
    price: {half:16,whole:30},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "loaf"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Loaf",
    status: "published"
  },
  //show show copy la the tag ==
  {
    id: "Loaf5",
    name: "Olive Loaf",
    description: "",
    price: {half:16.50,whole:31},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "loaf"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Loaf",
    status: "published"
  },
  {
    id: "Loaf6",
    name: "Assorted Seeds Loaf",
    description: "",
    price: {half:16,whole:30},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "loaf"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Loaf",
    status: "published"
  },
  {
    id: "Loaf7",
    name: "Black Sesame Loaf",
    description: "",
    price: {half:16,whole:30},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "loaf"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Loaf",
    status: "published"
  },
  {
    id: "Loaf8",
    name: "Tomato Basil Loaf",
    description: "",
    price: {half:16,whole:30},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "loaf"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Loaf",
    status: "published"
  },
  {
    id: "Loaf9",
    name: "Sweet Pumpkin Loaf",
    description: "",
    price: {half:16,whole:30},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "loaf"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Loaf",
    status: "published"
  },
  {
    id: "Loaf10",
    name: "Purple Potato Loaf",
    description: "",
    price: {half:16,whole:30},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "loaf"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Loaf",
    status: "published"
  },
  {
    id: "Loaf11",
    name: "Blueberry Orange Loaf",
    description: "",
    price: {half:16,whole:30},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "loaf"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Loaf",
    status: "published"
  },
  {
    id: "Loaf12",
    name: "Spinach Loaf",
    description: "",
    price: {half:16,whole:30},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "loaf"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Loaf",
    status: "published"
  },
  {
    id: "Loaf13",
    name: "Chocolate Loaf",
    description: "",
    price: {half:17,whole:32},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "loaf"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Loaf",
    status: "published"
  },
  {
    id: "Marble1",
    name: "Matcha Marble Bread",
    description: "",
    price: {normal:6},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Marble",
    status: "published"
  },
  {
    id: "Marble2",
    name: "Chocolate Marble Bread",
    description: "",
    price: {normal:6},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Marble",
    status: "published"
  },
  {
    id: "Marble3",
    name: "Coffee Marble Bread",
    description: "",
    price: {normal:6},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Marble",
    status: "published"
  },
  {
    id: "Baguette1",
    name: "Classic Baguette",
    description: "",
    price: {normal:13},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "baguette"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Baguette",
    status: "published"
  },
  {
    id: "Baguette2",
    name: "Spelt Baguette",
    description: "",
    price: {normal:14},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "baguette"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Baguette",
    status: "published"
  },
  {
    id: "Baguette3",
    name: "Wholemeal Baguette",
    description: "",
    price: {normal:14},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "baguette"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Baguette",
    status: "published"
  },
  {
    id: "Baguette4",
    name: "Rye Baguette",
    description: "",
    price: {normal:14},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "baguette"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Baguette",
    status: "published"
  },
  {
    id: "Country1",
    name: "Country Bread",
    description: "",
    price: {normal:17.90},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "country"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Country",
    status: "published"
  },
  {
    id: "Country2",
    name: "Sesame Country Bread",
    description: "",
    price: {normal:20.90},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "country"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Country",
    status: "published"
  },
  {
    id: "Sourdough1",
    name: "Rye Sourdough",
    description: "",
    price: {normal:18.90},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "sourdough"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Sourdough",
    status: "published"
  },
  {
    id: "Sourdough2",
    name: "Wholemeal Sourdough",
    description: "",
    price: {normal:18.90},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "sourdough"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Sourdough",
    status: "published"
  },
  {
    id: "Sourdough3",
    name: "Spelt Quinoa Sourdough",
    description: "",
    price: {normal:22.90},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "sourdough"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Sourdough",
    status: "published"
  },
  {
    id: "Ciabatta1",
    name: "Classic Ciabatta",
    description: "",
    price: {gram550:24,gram180:8},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "ciabatta"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Ciabatta",
    status: "published"
  },
  {
    id: "Ciabatta2",
    name: "Lavender Ciabatta",
    description: "",
    price: {normal:11.90},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "ciabatta"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Ciabatta",
    status: "published"
  },
  {
    id: "Ciabatta3",
    name: "Red Velvet Ciabatta",
    description: "",
    price: {normal:11.90},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "ciabatta"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Ciabatta",
    status: "published"
  },
  {
    id: "Ciabatta4",
    name: "Purple Potato Ciabatta",
    description: "",
    price: {normal:11.90},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "ciabatta"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Ciabatta",
    status: "published"
  },
  {
    id: "Ciabatta5",
    name: "Spinach Corn Ciabatta",
    description: "",
    price: {normal:11.90},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "ciabatta"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Ciabatta",
    status: "published"
  },
  {
    id: "Ciabatta6",
    name: "Olive Ciabatta",
    description: "",
    price: {normal:9},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "ciabatta"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Ciabatta",
    status: "published"
  },
  {
    id: "French1",
    name: "Dried Fruits French Bread",
    description: "",
    price: {normal:13},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "french"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "French",
    status: "published"
  },
  {
    id: "French2",
    name: "Walnut Raisin French Bread",
    description: "",
    price: {normal:13},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "french"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "French",
    status: "published"
  },
  {
    id: "French3",
    name: "Table French Bread",
    description: "",
    price: {normal:5.50},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "french"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "French",
    status: "published"
  },
  {
    id: "French4",
    name: "Chocolate Almond Cranberry French Bread",
    description: "",
    price: {normal:14},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "french"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "French",
    status: "published"
  },
  {
    id: "French5",
    name: "Fig Olive Walnut French Bread",
    description: "",
    price: {normal:15.50},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "french"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "French",
    status: "published"
  },
  {
    id: "Bread1",
    name: "Cinnamon Roll",
    description: "",
    price: {normal:6.50},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bread"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bread",
    status: "published"
  },
  {
    id: "Bun1",
    name: "Taro Bun",
    description: "",
    price: {normal:5.80},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun2",
    name: "Burger Bun",
    description: "",
    price: {normal:5},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun3",
    name: "Spinach Red Bean Bun",
    description: "",
    price: {normal:5.80},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun4",
    name: "Wholemeal Raisin Bun",
    description: "",
    price: {normal:5.50},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun5",
    name: "Tomato Basil Bun",
    description: "",
    price: {normal:5.50},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun6",
    name: "Carrot Raisin Bun",
    description: "",
    price: {normal:5.50},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun7",
    name: "Coconut Cream Bun",
    description: "",
    price: {normal:5.50},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun8",
    name: "Sweet Pumpkin Bun",
    description: "",
    price: {normal:7.50},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun9",
    name: "Sesame Walnut Bun",
    description: "",
    price: {normal:5.80},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun10",
    name: "Earl Grey Tea Bun",
    description: "",
    price: {normal:5.80},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun11",
    name: "Purple Sweet Potato Swirl Bun",
    description: "",
    price: {normal:5.50},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun12",
    name: "Pumpkin Bun",
    description: "",
    price: {normal:5},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun13",
    name: "Spinach Bun",
    description: "",
    price: {normal:5},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun14",
    name: "Sweet Corn Bun",
    description: "",
    price: {normal:5.50},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun15",
    name: "Curry Bun",
    description: "",
    price: {normal:6.80},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun16",
    name: "Pandan Coconut Bun",
    description: "",
    price: {normal:5.50},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun17",
    name: "Assorted Seeds Bun",
    description: "",
    price: {normal:5.80},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun18",
    name: "Peanut Butter Braided Bun",
    description: "",
    price: {normal:5.80},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "bun"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Bun",
    status: "published"
  },
  {
    id: "Bun18",
    name: "Peanut Butter Braided Bun",
    description: "",
    price: {normal:5.80},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "doughnut"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Doughnut",
    status: "published"
  },
  {
    id: "Doughnut1",
    name: "Cinnamon Sugar Doughnut",
    description: "",
    price: {normal:5},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "doughnut"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Doughnut",
    status: "published"
  },
  {
    id: "Doughnut2",
    name: "Matcha Glazed Doughnut",
    description: "",
    price: {normal:6.50},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "doughnut"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Doughnut",
    status: "published"
  },
  {
    id: "Doughnut3",
    name: "Chocolate Glazed Doughnut",
    description: "",
    price: {normal:6.50},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "doughnut"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Doughnut",
    status: "published"
  },
  {
    id: "Focaccia1",
    name: "Classic Focaccia",
    description: "",
    price: {normal:8.50},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "focaccia"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Focaccia",
    status: "published"
  },
  {
    id: "Focaccia2",
    name: "Potato Focaccia",
    description: "",
    price: {normal:8.50},
    tag: ["Unbleached wheat flour", "leaven", "rice milk", "filtered water", "oil", "wholemeal flour", "sugar", "flaxseed", "chia seed", "natural sea salt", "marble", "focaccia"],
    imageUrl: "../../assets/media/avatars/300-1.jpg",
    stockQuantity: 10,
    rating:3,
    category: "Focaccia",
    status: "published"
  },

];

export const sample_tags: any[] = [
  {
    name: "bread",
    count: 2,
  },
  {
    name: "beverage",
    count: 2,
  },
  {
    name: "cake",
    count: 2,
  },
];

export const sample_users: any[] = [
  {
    name: "quan",
    phone:"019-5864123",
    address: "Penang",
    email: "quan@gmail.com",
    userName: "quan",
    password: "12345",
    isAdmin: true,
    preference: [] = []
  },{
    name: "jane",
    phone:"012-3456789",
    address: "Kedah",
    email: "jane@gmail.com",
    userName: "jane",
    password: "12345",
    isAdmin: false,
    preference: [] = []
  }
  // {
  //   email:"jinx@gmail.com",
  //   name:"jinx",
  //   password:"123456",
  //   isAdmin:false,
  //   address:"bbbbbbbb",
  //   country:"Bahrain",
  //   phone:"0197968130",
  //   preference:[
  //     {product:'63273d3237d0da41949f3e68', rating:5},
  //     {product:'63307022e7893b24c17d8df1', rating:4},
  //     {product:'634d71012fe790023e2aafbd', rating:3}
  //   ]
  // }
];
